//! Normal-basis binary presentations at degrees 2, 4, and 8.
//!
//! [`Normal`] wraps a polynomial [`Poly`] basis element
//! `E` into its conjugate basis: bit `i` selects `E^(2^i)`, and one is all
//! `N` bits set. The descriptor pins both coordinate matrices; the inverse
//! columns come from bounded enumeration of the forward map, never from a
//! matrix solver.
//!
//! Smallest valid test instances: `E = 2` over `P = 0x7`, `E = 8` over
//! `P = 0x13`, and `E = 0x20` over [`AES`](super::poly::AES) and
//! [`REED_SOLOMON`](super::poly::REED_SOLOMON).
//!
//! ```compile_fail,E0080
//! // E = 1 has all conjugates equal to one, so the basis collapses.
//! let _ = fgf::Elem::<fgf::Gf<8, fgf::Normal<0x11B, 1>>>::from_raw(1);
//! ```

use super::description::{BinaryDescription, ByteLogExp};
use super::poly::Poly;
use super::{BinaryRepr, private};

/// A normal-basis presentation over `Poly<P>` generated by `E`.
///
/// `E` is a raw element of `Poly<P>`; bit `i` of the basis coordinates
/// selects `E^(2^i)`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Default, PartialOrd, Ord)]
pub struct Normal<const P: u128, const E: u8>;

impl<const P: u128, const E: u8> private::Sealed for Normal<P, E> {}

/// Conjugate powers of `E` in `Poly<P>` coordinates: `to_base[i]` is
/// `E^(2^i)`, with unused slots zero.
pub(crate) const fn to_base<const P: u128, const E: u8, const N: u8>() -> [u8; 8] {
    let desc = BinaryDescription::polynomial(N, P);
    let mut cols = [0u8; 8];
    let mut power = E as u64;
    let mut i = 0;
    while i < N as usize {
        #[allow(clippy::cast_possible_truncation)]
        let byte = power as u8;
        cols[i] = byte;
        power = desc.mul(power, power);
        i += 1;
    }
    cols
}

/// Inverse columns of a forward map by bounded enumeration.
///
/// For each polynomial basis vector `1 << j`, the unique basis word mapping
/// to it; the caller guarantees the map is bijective, so the search
/// terminates.
pub(crate) const fn inverse_columns(forward: [u8; 8], n: u8) -> [u8; 8] {
    let mut inverse = [0u8; 8];
    let mut j = 0;
    while j < n as usize {
        let target = 1u64 << j;
        let mut w = 0u64;
        loop {
            assert!(w < (1u64 << n), "basis map is not bijective");
            let mut image = 0u64;
            let mut i = 0;
            while i < 8 {
                if (w >> i) & 1 == 1 {
                    image ^= forward[i] as u64;
                }
                i += 1;
            }
            if image == target {
                #[allow(clippy::cast_possible_truncation)]
                let byte = w as u8;
                inverse[j] = byte;
                break;
            }
            w += 1;
        }
        j += 1;
    }
    inverse
}

macro_rules! normal_row {
    ($n:literal) => {
        impl<const P: u128, const E: u8> BinaryRepr<$n> for Normal<P, E> {
            const NAME: &'static str = "normal";
            const DESCRIPTION: &'static BinaryDescription = &BinaryDescription::append_basis(
                &BinaryDescription::polynomial($n, P),
                to_base::<P, E, $n>(),
                inverse_columns(to_base::<P, E, $n>(), $n),
            );
            const LOG_EXP: Option<&'static ByteLogExp> = None;
            const VALID: () = {
                assert!((E as u64) < (1u64 << $n), "normal element has excess bits");
                <Self as BinaryRepr<$n>>::DESCRIPTION.validate();
                assert!(
                    <Self as BinaryRepr<$n>>::DESCRIPTION.one() == (1u64 << $n) - 1,
                    "normal basis one is all bits set"
                );
            };
        }
    };
}

normal_row!(2);
normal_row!(4);

/// Transport the polynomial generator of `P` into basis coordinates.
pub(crate) const fn transported_generator<const P: u128, const E: u8, const N: u8>() -> u64 {
    let poly_desc = BinaryDescription::polynomial(N, P);
    let poly_gen = Poly::<P>::smallest_generator(&poly_desc);
    let from = inverse_columns(to_base::<P, E, N>(), N);
    let mut image = 0u64;
    let mut i = 0;
    while i < 8 {
        if (poly_gen >> i) & 1 == 1 {
            image ^= from[i] as u64;
        }
        i += 1;
    }
    image
}

use super::super::HasGenerator;
use super::Gf;

impl<const P: u128, const E: u8> HasGenerator for Gf<2, Normal<P, E>> {
    const GENERATOR_RAW: u8 = {
        let g = transported_generator::<P, E, 2>();
        assert!(
            <Normal<P, E> as BinaryRepr<2>>::DESCRIPTION.is_generator(g),
            "basis generator does not have full order"
        );
        #[allow(clippy::cast_possible_truncation)]
        let generator = g as u8;
        generator
    };
}

impl<const P: u128, const E: u8> HasGenerator for Gf<4, Normal<P, E>> {
    const GENERATOR_RAW: u8 = {
        let g = transported_generator::<P, E, 4>();
        assert!(
            <Normal<P, E> as BinaryRepr<4>>::DESCRIPTION.is_generator(g),
            "basis generator does not have full order"
        );
        #[allow(clippy::cast_possible_truncation)]
        let generator = g as u8;
        generator
    };
}

impl<const P: u128, const E: u8> HasGenerator for Gf<8, Normal<P, E>> {
    const GENERATOR_RAW: u8 = {
        let g = transported_generator::<P, E, 8>();
        assert!(
            <Normal<P, E> as BinaryRepr<8>>::DESCRIPTION.is_generator(g),
            "basis generator does not have full order"
        );
        #[allow(clippy::cast_possible_truncation)]
        let generator = g as u8;
        generator
    };
}

impl<const P: u128, const E: u8> BinaryRepr<8> for Normal<P, E> {
    const NAME: &'static str = "normal";
    const DESCRIPTION: &'static BinaryDescription = &BinaryDescription::append_basis(
        &BinaryDescription::polynomial(8, P),
        to_base::<P, E, 8>(),
        inverse_columns(to_base::<P, E, 8>(), 8),
    );
    const LOG_EXP: Option<&'static ByteLogExp> = Some(&ByteLogExp::build(
        &BinaryDescription::append_basis(
            &BinaryDescription::polynomial(8, P),
            to_base::<P, E, 8>(),
            inverse_columns(to_base::<P, E, 8>(), 8),
        ),
        {
            let poly_desc = BinaryDescription::polynomial(8, P);
            let poly_gen = Poly::<P>::smallest_generator(&poly_desc);
            let mut image = 0u64;
            let mut i = 0;
            let from = inverse_columns(to_base::<P, E, 8>(), 8);
            while i < 8 {
                if (poly_gen >> i) & 1 == 1 {
                    image ^= from[i] as u64;
                }
                i += 1;
            }
            image
        },
    ));
    const VALID: () = {
        <Self as BinaryRepr<8>>::DESCRIPTION.validate();
        assert!(
            <Self as BinaryRepr<8>>::DESCRIPTION.one() == 0xFF,
            "normal basis one is all bits set"
        );
        assert!(
            <Self as BinaryRepr<8>>::DESCRIPTION.is_generator({
                let poly_desc = BinaryDescription::polynomial(8, P);
                let poly_gen = Poly::<P>::smallest_generator(&poly_desc);
                let mut image = 0u64;
                let mut i = 0;
                let from = inverse_columns(to_base::<P, E, 8>(), 8);
                while i < 8 {
                    if (poly_gen >> i) & 1 == 1 {
                        image ^= from[i] as u64;
                    }
                    i += 1;
                }
                image
            }),
            "basis generator does not have full order"
        );
    };
}
